# Generated by Django 3.2.9 on 2021-11-09 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ebooks', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ebooks',
            name='Description',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='ebooks',
            name='title',
            field=models.CharField(max_length=140),
        ),
    ]
